# Historical Backtesting Configuration for LLM-Enhanced AWM Trading System

# Backtesting Period
backtest_period:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  timezone: "Asia/Kolkata"

# Portfolio Configuration
portfolio:
  initial_capital: 1000000  # ₹10,00,000
  max_position_size_pct: 0.10  # 10% maximum position size
  cash_reserve_pct: 0.20  # 20% minimum cash reserve

# Symbols to Test
symbols:
  - "RELIANCE"
  - "TCS"
  - "HDFCBANK"
  - "INFY"
  - "HINDUNILVR"

# Transaction Costs (Indian Markets)
transaction_costs:
  brokerage_pct: 0.001      # 0.1% brokerage
  stt_pct: 0.001            # Securities Transaction Tax
  exchange_charges_pct: 0.0001  # Exchange charges
  gst_pct: 0.00018          # GST on brokerage
  total_cost_pct: 0.00228   # Total ~0.228%

# Slippage Modeling
slippage:
  market_order_slippage_bps: 5    # 5 basis points for market orders
  volatility_multiplier: 1.5      # Increase slippage during high volatility
  liquidity_impact_threshold: 0.01 # 1% of average volume
  max_slippage_pct: 0.005         # Cap at 0.5%

# Trading Configuration
trading:
  strategies:
    llm_enhanced:
      config: "moderate"
      enable_llm: true
      llm_confidence_threshold: 0.6
      sentiment_weight: 0.15
      regime_weight: 0.10
    quantitative_only:
      config: "conservative"
      enable_llm: false
      disable_llm_insights: true

# Risk Management
risk_management:
  max_daily_trades: 20
  max_sector_exposure_pct: 0.25  # 25% per sector
  stop_loss_pct: 0.05            # 5% stop loss
  take_profit_pct: 0.10          # 10% take profit
  
  # Circuit breakers
  circuit_breakers:
    daily_loss_limit_pct: 0.02   # 2% daily loss limit
    weekly_loss_limit_pct: 0.05  # 5% weekly loss limit
    monthly_loss_limit_pct: 0.10 # 10% monthly loss limit

# Performance Metrics Configuration
performance_metrics:
  risk_free_rate: 0.06  # 6% risk-free rate for India
  benchmark_return: 0.12  # 12% expected market return
  
  # Calculation windows
  rolling_sharpe_window: 30    # 30-day rolling Sharpe ratio
  volatility_window: 20        # 20-day volatility window
  drawdown_threshold: 0.05     # 5% drawdown threshold for analysis

# Statistical Testing Configuration
statistical_tests:
  significance_level: 0.05     # 5% significance level
  bootstrap_iterations: 1000   # Bootstrap iterations for Sharpe ratio test
  min_sample_size: 30          # Minimum sample size for tests

# LLM Performance Configuration
llm_performance:
  latency_sla_ms: 500          # 500ms latency SLA
  confidence_threshold: 0.7    # Minimum confidence for high-confidence trades
  sentiment_accuracy_threshold: 0.65  # Minimum sentiment accuracy
  regime_accuracy_threshold: 0.70     # Minimum regime detection accuracy

# Edge Case Testing Configuration
edge_case_testing:
  high_volatility_periods:
    - start: "2023-03-01"
      end: "2023-03-31"
      event: "Banking sector stress"
    - start: "2023-10-01"
      end: "2023-10-31"
      event: "Geopolitical tensions"
  
  stress_test_scenarios:
    - name: "Market Crash"
      description: "Simulate 20% market decline"
      duration_days: 5
    - name: "High Volatility"
      description: "Simulate VIX > 30 conditions"
      duration_days: 10
    - name: "Low Liquidity"
      description: "Simulate 50% volume reduction"
      duration_days: 3

# Production Readiness Criteria
production_readiness:
  performance_criteria:
    min_return_improvement: 0.01      # 1% minimum return improvement
    min_sharpe_improvement: 0.05      # 0.05 minimum Sharpe improvement
    max_drawdown_tolerance: 0.15      # 15% maximum drawdown
    min_win_rate: 0.55               # 55% minimum win rate
  
  risk_criteria:
    max_var_95: 0.03                 # 3% maximum VaR (95%)
    max_position_violations: 2        # Maximum position size violations
    min_diversification_ratio: 0.7   # Minimum diversification ratio
  
  llm_criteria:
    min_sentiment_accuracy: 0.65     # 65% minimum sentiment accuracy
    min_regime_accuracy: 0.70        # 70% minimum regime accuracy
    max_latency_p95: 500             # 500ms maximum p95 latency
    min_uptime: 0.995                # 99.5% minimum uptime
  
  overall_score_threshold: 0.70      # 70% minimum overall score for production

# Deployment Configuration
deployment:
  phased_rollout:
    phase_1:
      duration_weeks: 4
      allocation_pct: 0.10           # 10% allocation
      monitoring: "real-time"
    phase_2:
      duration_weeks: 4
      allocation_pct: 0.25           # 25% allocation
      monitoring: "daily"
    phase_3:
      duration_weeks: 4
      allocation_pct: 0.50           # 50% allocation
      monitoring: "daily"
    phase_4:
      duration_weeks: 4
      allocation_pct: 1.00           # 100% allocation
      monitoring: "weekly"
  
  success_criteria:
    return_improvement: 0.01         # 1% return improvement
    max_drawdown: 0.15              # 15% maximum drawdown
    sharpe_ratio: 1.0               # Minimum Sharpe ratio
    latency_compliance: 0.95        # 95% latency compliance
  
  stop_conditions:
    max_drawdown_breach: 0.20       # 20% drawdown breach
    consecutive_losses: 5           # 5 consecutive loss days
    latency_degradation: 0.90       # 90% latency compliance
    system_error_rate: 0.05         # 5% system error rate

# Monitoring and Alerting
monitoring:
  metrics:
    performance:
      - "daily_returns"
      - "cumulative_returns"
      - "rolling_sharpe_ratio"
      - "maximum_drawdown"
      - "win_rate"
    
    risk:
      - "portfolio_volatility"
      - "value_at_risk_95"
      - "position_concentration"
      - "sector_exposure"
      - "market_correlation"
    
    llm:
      - "inference_latency_p95"
      - "inference_latency_p99"
      - "sentiment_accuracy"
      - "decision_confidence"
      - "service_uptime"
    
    operational:
      - "trade_execution_rate"
      - "order_fill_rate"
      - "system_error_rate"
      - "data_feed_reliability"
  
  alert_thresholds:
    performance:
      daily_return_loss: -0.02      # -2% daily return
      drawdown_warning: 0.10        # 10% drawdown warning
      sharpe_degradation: 0.20      # 20% Sharpe ratio degradation
    
    risk:
      var_breach: true              # VaR breach alert
      position_limit_breach: true   # Position limit breach
      sector_concentration: 0.30    # 30% sector concentration
    
    llm:
      latency_breach: 600           # 600ms latency breach
      accuracy_degradation: 0.10    # 10% accuracy degradation
      service_downtime: 300         # 5 minutes downtime
    
    operational:
      error_rate_high: 0.02         # 2% error rate
      execution_failure: 0.05       # 5% execution failure rate

# Reporting Configuration
reporting:
  formats:
    - "json"
    - "txt"
    - "csv"  # For trade-level data
  
  sections:
    - "executive_summary"
    - "performance_analysis"
    - "risk_analysis"
    - "statistical_tests"
    - "llm_effectiveness"
    - "edge_case_analysis"
    - "production_readiness"
    - "deployment_recommendations"
  
  output_directory: "test_results"
  include_charts: false  # Set to true if chart generation is implemented
  
# Server Configuration
servers:
  market_data: "http://localhost:8001"
  signal_generation: "http://localhost:8004"
  decision_engine: "http://localhost:8005"
  llm_market_intelligence: "http://localhost:8007"
  
  timeouts:
    market_data: 30      # 30 seconds
    signal_generation: 60 # 60 seconds
    decision_engine: 60   # 60 seconds
    llm_intelligence: 120 # 120 seconds

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/historical_backtesting.log"
  max_file_size: "100MB"
  backup_count: 5
